"""create interview tables

Revision ID: 25a36a3a7fb3
Revises: 051bbf928bbe
Create Date: 2026-05-05 00:53:12.516731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25a36a3a7fb3'
down_revision: Union[str, Sequence[str], None] = '051bbf928bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'cancelled', name='interview_status'), server_default=sa.text("'draft'::interview_status"), nullable=False),
    sa.Column('interview_type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('interview_context_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('question_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interview_sessions_created_at_desc', 'interview_sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_interview_sessions_status', 'interview_sessions', ['status'], unique=False)
    op.create_index('ix_interview_sessions_user_id', 'interview_sessions', ['user_id'], unique=False)
    op.create_table('interview_turns',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_type', sa.Enum('candidate', 'interviewer', 'system', name='speaker_type'), nullable=False),
    sa.Column('turn_kind', sa.Enum('question', 'answer', 'system_event', name='turn_kind'), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_no', name='uq_interview_turns_session_sequence')
    )
    op.create_index('ix_interview_turns_created_at', 'interview_turns', ['created_at'], unique=False)
    op.create_index('ix_interview_turns_session_id', 'interview_turns', ['session_id'], unique=False)
    op.create_index('ix_interview_turns_speaker_type', 'interview_turns', ['speaker_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interview_turns_speaker_type', table_name='interview_turns')
    op.drop_index('ix_interview_turns_session_id', table_name='interview_turns')
    op.drop_index('ix_interview_turns_created_at', table_name='interview_turns')
    op.drop_table('interview_turns')
    op.drop_index('ix_interview_sessions_user_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_status', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_created_at_desc', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
