"""added role in jd table

Revision ID: 443e853356eb
Revises: c6ff1e60502b
Create Date: 2026-04-08 23:44:26.558220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "443e853356eb"
down_revision: Union[str, Sequence[str], None] = "c6ff1e60502b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_descriptions", sa.Column("role", sa.String(length=255), nullable=True)
    )
    op.execute(
        "UPDATE job_descriptions SET role = 'Software Engineer' WHERE role IS NULL"
    )

    op.alter_column(
        "job_descriptions", "role", existing_type=sa.String(length=255), nullable=False
    )

    op.execute(
        "UPDATE job_descriptions SET raw_text = '' WHERE raw_text IS NULL"
    )

    op.alter_column(
        "job_descriptions", "raw_text", existing_type=sa.TEXT(), nullable=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job_descriptions", "raw_text", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_column("job_descriptions", "role")
    # ### end Alembic commands ###
