"""updated resume and file

Revision ID: 615f5047b24b
Revises: a6595acda66a
Create Date: 2026-04-02 05:14:27.856746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615f5047b24b'
down_revision: Union[str, Sequence[str], None] = 'a6595acda66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('resume', 'job_description', 'audio', 'report_export', name='file_kind'), nullable=False),
    sa.Column('storage_key', sa.String(length=2048), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_kind', 'files', ['kind'], unique=False)
    op.create_index('ix_files_user_id', 'files', ['user_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_descriptions_company_name', 'job_descriptions', ['company_name'], unique=False)
    op.create_index('ix_job_descriptions_user_id', 'job_descriptions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('version_label', sa.String(length=255), nullable=True),
    sa.Column('parse_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='parse_status'), server_default=sa.text("'pending'::parse_status"), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resumes_parse_status', 'resumes', ['parse_status'], unique=False)
    op.create_index('ix_resumes_user_id', 'resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resumes_user_id', table_name='resumes')
    op.drop_index('ix_resumes_parse_status', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('ix_job_descriptions_user_id', table_name='job_descriptions')
    op.drop_index('ix_job_descriptions_company_name', table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index('ix_files_user_id', table_name='files')
    op.drop_index('ix_files_kind', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
