"""made title and company name not null field

Revision ID: 6bfc5465ac3e
Revises: 443e853356eb
Create Date: 2026-04-14 01:36:44.183142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfc5465ac3e'
down_revision: Union[str, Sequence[str], None] = '443e853356eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_descriptions', 'title',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('job_descriptions', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_descriptions', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('job_descriptions', 'title',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
