"""added parsed_resume table

Revision ID: c6ff1e60502b
Revises: e4b9c2f8a1d3
Create Date: 2026-04-03 02:33:29.729788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ff1e60502b'
down_revision: Union[str, Sequence[str], None] = 'e4b9c2f8a1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_resumes_resume_id'), table_name='parsed_resumes')
    op.create_unique_constraint(None, 'parsed_resumes', ['resume_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parsed_resumes', type_='unique')
    op.create_index(op.f('ix_parsed_resumes_resume_id'), 'parsed_resumes', ['resume_id'], unique=True)
    # ### end Alembic commands ###
